package com.vitalsoft.sabretooth.config;

import java.io.*;
import java.util.*;

/**
 * Represents a .sabreconf project configuration file.
 * Simple key=value format with sections [section].
 */
public class SabreConf {
    private final Map<String, String> values = new LinkedHashMap<>();
    private File file;

    // Keys
    public static final String KEY_PROJECT_NAME    = "project.name";
    public static final String KEY_PACKAGE_NAME    = "project.package";
    public static final String KEY_MIN_SDK         = "android.minSdk";
    public static final String KEY_TARGET_SDK      = "android.targetSdk";
    public static final String KEY_COMPILE_SDK     = "android.compileSdk";
    public static final String KEY_VERSION_CODE    = "android.versionCode";
    public static final String KEY_VERSION_NAME    = "android.versionName";
    public static final String KEY_BUILD_TYPE      = "build.type";        // gradle | eclipse
    public static final String KEY_GRADLE_PATH     = "build.gradlePath";
    public static final String KEY_JDK_PATH        = "build.jdkPath";
    public static final String KEY_ANDROID_JAR     = "build.androidJar";
    public static final String KEY_KEYSTORE_PATH   = "sign.keystorePath";
    public static final String KEY_KEYSTORE_ALIAS  = "sign.keystoreAlias";
    public static final String KEY_OUTPUT_DIR      = "build.outputDir";
    public static final String KEY_EXTRA_GRADLE    = "build.extraGradleArgs";
    public static final String KEY_MAIN_ACTIVITY   = "android.mainActivity";
    public static final String KEY_PROJECT_TYPE    = "project.type";      // gradle | eclipse

    public SabreConf() {
        setDefaults();
    }

    public SabreConf(File file) throws IOException {
        setDefaults();
        this.file = file;
        load(file);
    }

    private void setDefaults() {
        values.put(KEY_PROJECT_NAME, "MyApp");
        values.put(KEY_PACKAGE_NAME, "com.example.myapp");
        values.put(KEY_MIN_SDK, "21");
        values.put(KEY_TARGET_SDK, "34");
        values.put(KEY_COMPILE_SDK, "34");
        values.put(KEY_VERSION_CODE, "1");
        values.put(KEY_VERSION_NAME, "1.0");
        values.put(KEY_BUILD_TYPE, "debug");
        values.put(KEY_GRADLE_PATH, "");
        values.put(KEY_JDK_PATH, "");
        values.put(KEY_ANDROID_JAR, "");
        values.put(KEY_KEYSTORE_PATH, "");
        values.put(KEY_KEYSTORE_ALIAS, "");
        values.put(KEY_OUTPUT_DIR, "build/outputs/apk");
        values.put(KEY_EXTRA_GRADLE_ARGS, "");

        values.put(KEY_MAIN_ACTIVITY, "MainActivity");
        values.put(KEY_PROJECT_TYPE, "gradle");
    }
    
    public static final String KEY_EXTRA_GRADLE_ARGS = "build.extraGradleArgs";

    public String get(String key) {
        return values.getOrDefault(key, "");
    }

    public void set(String key, String value) {
        values.put(key, value == null ? "" : value);
    }

    public void load(File f) throws IOException {
        this.file = f;
        try (BufferedReader br = new BufferedReader(new FileReader(f))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#") || line.startsWith("[")) continue;
                int eq = line.indexOf('=');
                if (eq > 0) {
                    String key = line.substring(0, eq).trim();
                    String val = line.substring(eq + 1).trim();
                    values.put(key, val);
                }
            }
        }
    }

    public void save(File f) throws IOException {
        this.file = f;
        try (PrintWriter pw = new PrintWriter(new FileWriter(f))) {
            pw.println("# SabreTooth IDE Project Configuration");
            pw.println("# Generated by SabreTooth IDE - do not edit manually unless you know what you're doing");
            pw.println();
            pw.println("[project]");
            writeKey(pw, KEY_PROJECT_NAME);
            writeKey(pw, KEY_PACKAGE_NAME);
            writeKey(pw, KEY_PROJECT_TYPE);
            writeKey(pw, KEY_MAIN_ACTIVITY);
            pw.println();
            pw.println("[android]");
            writeKey(pw, KEY_MIN_SDK);
            writeKey(pw, KEY_TARGET_SDK);
            writeKey(pw, KEY_COMPILE_SDK);
            writeKey(pw, KEY_VERSION_CODE);
            writeKey(pw, KEY_VERSION_NAME);
            pw.println();
            pw.println("[build]");
            writeKey(pw, KEY_BUILD_TYPE);
            writeKey(pw, KEY_GRADLE_PATH);
            writeKey(pw, KEY_JDK_PATH);
            writeKey(pw, KEY_ANDROID_JAR);
            writeKey(pw, KEY_OUTPUT_DIR);
            writeKey(pw, KEY_EXTRA_GRADLE_ARGS);
            pw.println();
            pw.println("[signing]");
            writeKey(pw, KEY_KEYSTORE_PATH);
            writeKey(pw, KEY_KEYSTORE_ALIAS);
        }
    }

    private void writeKey(PrintWriter pw, String key) {
        pw.println(key + " = " + values.getOrDefault(key, ""));
    }

    public void save() throws IOException {
        if (file != null) save(file);
    }

    public File getFile() { return file; }
}
